language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    # Scala 2.12
    - jdk: openjdk8
      scala: 2.12.12
      env: TEST_SPARK_VERSION="3.0.0"
    - jdk: openjdk8
      scala: 2.12.12
      env: TEST_SPARK_VERSION="3.0.1"
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "test:scalastyle"
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
after_success:
  - bash <(curl -s https://codecov.io/bash)
